---
include:
  # White
  - board: nice_nano_v2
    shield: corne_left
    kconfig-files:
      - config/corne_white.conf
    artifact-name: corne-white
  - board: nice_nano_v2
    shield: corne_right
    kconfig-files:
      - config/corne_white.conf
    artifact-name: corne-white
  - board: nice_nano_v2
    shield: settings_reset
    kconfig-files:
      - config/corne_white.conf
    artifact-name: corne-white

  # Purple
  - board: nice_nano_v2
    shield: corne_left
    kconfig-files:
      - config/corne_purple.conf
    artifact-name: corne-purple
  - board: nice_nano_v2
    shield: corne_right
    kconfig-files:
      - config/corne_purple.conf
    artifact-name: corne-purple
  - board: nice_nano_v2
    shield: settings_reset
    kconfig-files:
      - config/corne_purple.conf
    artifact-name: corne-purple
