name: Build Corne Variants

on: [push, pull_request, workflow_dispatch]

jobs:
  prepare-white:
    name: Prepare White config
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.push.outputs.ref }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy white build.yaml
        run: cp build-white.yaml config/build.yaml

      - name: Commit temporary build.yaml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add config/build.yaml
          git commit -m "Use white build.yaml"
          git push origin HEAD:temp-white || true

      - name: Set ref output
        id: push
        run: echo "ref=temp-white" >> $GITHUB_OUTPUT

  build-white:
    name: Build Corne White
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    needs: prepare-white
    with:
      ref: ${{ needs.prepare-white.outputs.ref }}

  prepare-purple:
    name: Prepare Purple config
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.push.outputs.ref }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy purple build.yaml
        run: cp build-purple.yaml config/build.yaml

      - name: Commit temporary build.yaml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add config/build.yaml
          git commit -m "Use purple build.yaml"
          git push origin HEAD:temp-purple || true

      - name: Set ref output
        id: push
        run: echo "ref=temp-purple" >> $GITHUB_OUTPUT

  build-purple:
    name: Build Corne Purple
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    needs: prepare-purple
    with:
      ref: ${{ needs.prepare-purple.outputs.ref }}
