name: Build Dual Corne Configs

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        variant:
          - name: "3p1 Corne White"
            ble_name: "Corne-White"
          - name: "3p1 Corne Purple"
            ble_name: "Corne-Purple"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout user config
        uses: actions/checkout@v4

      - name: Set BLE device name
        run: echo "CONFIG_ZMK_BLE_DEVICE_NAME=\"${{ matrix.variant.ble_name }}\"" > config/ble_name.conf

      - name: Merge BLE name into build config
        run: |
          echo "include: config/ble_name.conf" >> build.yaml

      - name: Build ZMK firmware
        uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
        with:
          build_dir: build/${{ matrix.variant.ble_name }}

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.variant.ble_name }}
          path: build/${{ matrix.variant.ble_name }}/firmware.zip
